include: package:flutter_lints/flutter.yaml
analyzer:
  exclude: 
    - example/

linter:
  rules:
    - sort_child_properties_last: true
    - sort_constructors_first: true
    - prefer_single_quotes: true

