name: fp_util
description: Utilities and Extensions for num,BuildContext,EdgeInsets,File,String. constants for horizontal and vertical spacing.
version: 1.0.17

homepage: https://mkcli.kishormainali.com/
repository: https://github.com/kishormainali/fp_util

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  mime: ^1.0.4

  # image picker
  image_picker: ">=0.8.9 <2.0.0"

  # file picker
  file_picker: ^5.3.2

  # svg
  flutter_svg: ^2.0.7

  freezed_annotation: ^2.2.0

  path: ^1.8.3
  intl: ">=0.18.0 <=1.0.0"

  logger: ^1.4.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^2.0.1
  freezed: ^2.3.5
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
