name: fp_util
description: Utilities and Extensions for num,BuildContext,EdgeInsets,File,String. constants for horizontal and vertical spacing.
version: 2.1.2
homepage: https://mkcli.kishormainali.com/
repository: https://github.com/kishormainali/fp_util
topics: ['flutter','utility', 'extensions', 'spacing','tagsinputfield']

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  mime: ^1.0.4

  # image picker
  image_picker: ">=1.0.0 <2.0.0"

  # file picker
  file_picker: ^6.1.1

  # svg
  flutter_svg: ^2.0.9

  freezed_annotation: ^2.4.1

  path: ^1.8.3
  intl: ">=0.18.0 <=1.0.0"

  logger: ^2.0.2+1
  equatable: ^2.0.5

  mask_text_input_formatter: ^2.5.0

  gap: ^3.0.1

  uuid: ^4.2.1


dev_dependencies:
  flutter_lints: ^3.0.1
  freezed: ^2.4.5
  build_runner: ">=2.4.0 <=3.0.0"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
