name: fp_util
description: Utilities and Extensions for num,BuildContext,EdgeInsets,File,String. constants for horizontal and vertical spacing.
version: 2.2.0
homepage: https://mkcli.kishormainali.com/
repository: https://github.com/kishormainali/fp_util
issue_tracker: https://github.com/kishormainali/fp_util/issues
topics:
  - extensions
  - tags-input-field
  - utilities
  - spacing
  - widgets


environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  mime: ^1.0.5

  # image picker
  image_picker: ^1.0.7

  # file picker
  file_picker: ^6.1.1

  # svg
  flutter_svg: ^2.0.9

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  path: any
  intl: any

  equatable: ^2.0.5

  mask_text_input_formatter: ^2.8.0

  gap: ^3.0.1

  uuid: any

  flutter_animate: ^4.5.0

  collection: any

  io: ^1.0.4

  dio: ^5.4.0


dev_dependencies:
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
