# .github/workflows/publish.yml
name: Publish to pub.dev



on:

  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*' # for tags like: 'v1.2.3'



jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
      contents: read
    steps:

      # Checkout repository
      - uses: actions/checkout@v4
      # setup auth
      - name: Setup Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: true
          project_id: 'pub-dev-413813'
          workload_identity_provider: 'projects/992940971615/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account_email: 'github-actions@pub-dev-413813.iam.gserviceaccount.com'
      # Setup flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      # Publishing...
      - name: Publish to pub.dev
        run: dart pub publish -f
