# .github/workflows/publish.yml
name: Publish to pub.dev



on:

  workflow_call:
    inputs:
      environment:
        description: if specified, the workflow is required to be run in this environment (with additional approvals)
        required: false
        type: string
      project_id:
        description: The project ID
        required: true
        type: string
      workload_identity_provider:
        description: The workload identity provider
        required: true
        type: string

  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*' # for tags like: 'v1.2.3'



jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
      contents: read

    environment: ${{ inputs.environment }}

    steps:

      # Checkout repository
      - uses: actions/checkout@v4
      # setup auth
      - name: Setup Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: true
          project_id: ${{ inputs.project_id }}
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
      # Setup flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get
      # Publishing...
      - name: Publish to pub.dev
        run: dart pub publish -f
