# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*' # for tags like: 'v1.2.3'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pub.dev
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      # Checkout repository
      - uses: actions/checkout@v4
      # Setup flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      # Publishing...
      - name: Publish to pub.dev
        run: dart pub publish -f
